site_url: "https://xhenos.netlify.app"
logo_url: "https://xhenos.netlify.app/ogimage.png"
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img/

backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  open_authoring: true
  squash_merges: true
  commit_messages:
    create: "🚀 Create {{collection}} '{{slug}}'"
    update: "🚀 Update {{collection}} '{{slug}}'"
    delete: "🚀 Delete {{collection}} '{{slug}}'"
    uploadMedia: "🚀 Upload '{{path}}'"
    deleteMedia: "🚀 Delete '{{path}}'"
    openAuthoring: "{{message}}"

collections:
  - name: faq
    label: FAQ
    description: Frequently Asked Questions
    folder: content/help/faq
    extension: md
    format: yaml-frontmatter
    create: false
    slug: "{{slug}}"
    preview_path: "help/faq/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }


  - name: guides
    label: Guides
    label_singular: Guide
    description: User guides
    folder: content/help/guides
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    preview_path: "help/guides/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }


  - name: forks
    label: Forks
    label_singular: Fork
    description: Tachiyomi forks
    folder: content/forks
    extension: md
    format: yaml-frontmatter
    create: false
    slug: "{{slug}}"
    preview_path: "forks/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }


  - name: sandbox
    label: Sandbox
    description: Playground area
    folder: content/sandbox
    extension: md
    format: yaml-frontmatter
    create: true
    slug: "{{slug}}"
    preview_path: "sandbox/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Body",
          name: "body",
          widget: "markdown",
          buttons: ["bold", "italic", "code", "link", "heading-two", "heading-three", "heading-four", "quote", "bulleted-list", "numbered-list"],
          minimal: true,
        }
