backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "MarkdownPage"
    label: "Markdown Page"
    folder: "content"
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
