backend:
  name: github
  repo: xhenos/tachiyomi-website
  branch: gridsome
  commit_messages:
    create: "🚀 Create {{collection}} “{{slug}}”"
    update: "🚀 Update {{collection}} “{{slug}}”"
    delete: "🚀 Delete {{collection}} “{{slug}}”"
    uploadMedia: "🚀 Upload “{{path}}”"
    deleteMedia: "🚀 Delete “{{path}}”"
    openAuthoring: "{{message}}"

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "MarkdownPage"
    label: "Markdown Page"
    folder: "content"
    create: true
    nested:
      depth: 100
      summary: "{{title}}"
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
